# Generated by Django 4.1.7 on 2023-05-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('song', models.FileField(blank=True, null=True, upload_to='lyre_songs/')),
                ('lyrics', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
